### ISSUE TITLE
no_std support

### ISSUE THREAD

**Issue by nickbabcock** [nickbabcock/highway-rs#32]
Discussed [a bit here](https://github.com/nickbabcock/highway-rs/pull/30#issuecomment-703899731):

> > I have another branch with no_std support for the PortableHash
>
> Nice! One thing to note is that [SIMD instructions should still be available on core, afaik](https://doc.rust-lang.org/stable/core/arch/x86_64/index.html). What's not available is [`is_x86_feature_detected`](https://doc.rust-lang.org/stable/std/macro.is_x86_feature_detected.html) so it seems possible that one can continue using `AvxHash::force_new` on `no_std` (and have `AvxHash::new` return `None`). But we can talk about this more on the PR when you have it situated.

cc @jRimbault

Just creating this issue to track the request so I don't forget about this.

**Comment by jRimbault** [comment]
I'm sorry I haven't gotten back to it (I've really gotten into Hades the game..) :/

**Comment by nickbabcock** [comment]
Haha, no worries. I too get fixated on games and I didn't expect after creating this issue that I'd complete it -- but I couldn't get it out of my head
