### ISSUE TITLE
Excessive overhead in HighwayHasher for small payloads

### ISSUE THREAD

**Issue by nickbabcock** [nickbabcock/highway-rs#67]
The `HighwayHasher` facade will choose the best hashing implementation at runtime based on the underlying CPU capabilities.

I recently benchmarked the facade. At payloads under 1KB, the facade throughput can be twice as slow as the underlying AVX implementation. Of course, some overhead should be expected from the facade, but this is excessive. And such a large of a caveat shouldn't be present for the main entrypoint of the library.

Doing some profiling, most of the overhead comes from initialization where there is a `memcpy` of the implementation into `HighwayHasher` and since the internal implementations weigh ~192 bytes, this memcpy can be significant.

Not sure of the best way to solve this, but if I don't think of a good way, there's always the alternative of creating one-shot functions that can use a more traditional indirect function approach like [what is used memchr](https://github.com/BurntSushi/memchr/blob/be564d425bfcabd2c9925a8a360f4a62b866bb90/src/memchr/x86/mod.rs#L35)

**Comment by Sam-Sims** [comment]
Hello! Sorry to comment on an older/closed issue, but in light of this issue and the fix - are the benchmarks on the README page for smaller payloads still accurate?

My use case is building a hash from a vector of u64 - something like
```rust
fn hash(hashes: &[u64]) -> u64 {
    let key = Key([1, 2, 3, 4]);
    let mut hasher = HighwayHasher::new(key);
    for &hash in hashes {
        hasher.write_u64(hash);
    }
    hasher.finalize64()
}
```

I wondered if there would be a performance impact due to the smaller size of u64?

**Comment by nickbabcock** [comment]
Yeah I can run the benchmarks again, but in the meantime you can multiply the throughput by 2 for payloads of 64 bytes or less.

Highwayhash is fast, but only you can answer if it fits your use case. In general, the more data you give it, the higher the throughput.
