### ISSUE TITLE
U64 input

### ISSUE THREAD

**Issue by NN-Binary** [nickbabcock/highway-rs#9]
Hi,

Thanks for this awesome crate.
I'm using HighwayHash but I'd like to input u64 instead of u8 without having to use Transmute.

Would it be possible for you to integrate the possibility in your crate? That would be so helpful!

Thank you

**Comment by nickbabcock** [comment]
You should be able to use slice from raw parts safely.

```rust
let orig: [u64; 2] = [1, 2];
let ptr = orig.as_ptr() as *const u8;
let new_len = orig.len() * size_of::<u64>();
let data: &[u8] = unsafe { slice::from_raw_parts(ptr, new_len) };

let key = Key([1, 2, 3, 4]);
let hash = HighwayBuilder::new(&key).hash128(data);

println!("{:?}", hash);
```

But if I'm understanding you correctly, you want to be able to do the following, right? 😄 :

```rust
let orig: [u64; 2] = [1, 2];
let key = Key([1, 2, 3, 4]);
let hash = HighwayBuilder::new(&key).hash128(&orig[..]);

println!("{:?}", hash);
```

I think this can be accomplished by introducing a trait and providing default implementations, but I'd want to survey other rust hashing libraries to see if there is precedent

**Comment by HandleMaser** [comment]
Thanks for the help :)

And yes exactly.
Also the output as u64;4 would be awesome.

**Comment by nickbabcock** [comment]
Looking at other hashing libraries, all of them are consistent in accepting a byte slice (`&[u8]`), so I'm most likely going to keep that interface.

It is less consistent in return types:

- Currently 256bits are returned as a u128 pair
- Other rust hashing libraries that return large hashes store the result in a mutable byte slice
- The [official highwayhash library uses [u64; 4]](https://github.com/google/highwayhash/blob/9099074416ebc926c9e5e6f5143db92ebd9b4c03/highwayhash/hh_types.h#L38-L41):

I think it wouldn't be a bad compromise if the API allowed a return of [u64; 4] to remain consistent with the official implementation.

**Comment by pakipaki2000** [comment]
i'm actually in need of that too! I Never got the chance to ask you about it.

**Comment by nickbabcock** [comment]
> 
> 
> i'm actually in need of that too! I Never got the chance to ask you about it.

In need of what? Having `&[u64]` as input or `[u64; 4]` as output? 

Care to elaborate on your use case?

**Comment by HandleMaser** [comment]
Actually both for me, as U64;4 is way faster than u8;32 on massive amount of data.
Use case is optimizing it for 64 bits CPU and targets

**Comment by nickbabcock** [comment]
> Actually both for me, as U64;4 is way faster than u8;32 on massive amount of data.

Ah I've become confused, so just to be explicit:

If we're talking about input, internally it doesn't matter if the data is processed in `&[u64]` or `&[u8]` chunks as the data is loaded in avx registers via:

```rust
_mm256_loadu_si256(packet.as_ptr() as *const __m256i)
```

The only thing that matters is if it is 256bits, which both `[u64;4]` and `[u8;32]` satisfy.

---

If we're talking output. I do favor the output `[u64;4]` over `[u8;32]` as then it remains consistent with the official cpp implementation. I'm a bit skeptical on any performance benefit though, but I'd be convinced by a use that demonstrated a bottleneck in `slice::from_raw_parts`

**Comment by HandleMaser** [comment]
Yeah I was actually talking for the output mostly. 
performances increases are real, try it yourself with a standard loop.

**Comment by nickbabcock** [comment]
Ok, benchmark:

```rust
#[macro_use]
extern crate criterion;

use criterion::Criterion;
use criterion::black_box;

fn u64_sum() -> u64 {
    let arr = [1u64; 4];
    arr.into_iter().sum()
}

fn u8_sum() -> u8 {
    let arr = [1u8; 32];
    arr.into_iter().sum()
}

fn criterion_benchmark(c: &mut Criterion) {
    c.bench_function("u64_sum", |b| b.iter(|| for _ in 0..10000 { black_box(u64_sum()); }));
    c.bench_function("u8_sum", |b| b.iter(|| for _ in 0..10000 { black_box(u8_sum()); }));
}

criterion_group!(benches, criterion_benchmark);
criterion_main!(benches);
```

Results were that iterating over `[u64;4]` and and `[u8;32]` were the equivalent (sometimes u64 was reported as faster, other times u8)
